version: '3.7'

services:
  helpdesk:
    image: openjdk:20-jdk-slim
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helpdesk
    networks:
      - mynetwork
    ports:
      - 8080:8080
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - mynetwork
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser

networks:
  mynetwork: